# Custom Language File for Launcher Customizer

[ejs.app]
title = "RevixMC Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU REVIXMC LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "Copyright Â© 2025 RevixMC Studios"
